enum Category {
  APPLIANCES = "APPLIANCES",
  SPORTS = "SPORTS",
  CLOTHES = "CLOTHES",
  GAMES = "GAMES",
  HOME_AND_KITCHEN = "HOME_AND_KITCHEN",
  ELECTRONICS = "ELECTRONICS",
  FOOD = "FOOD",
  COMPUTERS = "COMPUTERS",
  ART = "ART",
  OFFICE = "OFFICE"
}

export default Category;